### ISSUE TITLE
Dockerization of the django app

### ISSUE THREAD

**Issue by mhmdahmedfathi** [InternetHealthReport/ihr-django#26]
I ask if I can start containerizing the app so it will be useful to all devices and will be more easy for the user to start the project

**Comment by mhmdahmedfathi** [comment]
@romain-fontugne Can you it to me if it is applicable ?

**Comment by romain-fontugne** [comment]
yes, please go ahead. I wonder how the configuration of the django app will be passed to the container?

**Comment by mhmdahmedfathi** [comment]
I have made a Docker compose file that will run a container that has 3 images inside (Django, Postgres, and Redis) and each one refers to its own folders or configurations.

**Comment by vishant007** [comment]
Hey,I want to contribute on this project and this issue through GSOC-2023,here is my portfolio, once I understand the project and its repository structure I can contribute to it,just need mentorship and little guidance to understand project structure.

Portfolio: https://vishant-n-shah.vercel.app/
