### ISSUE TITLE
User Management System 

### ISSUE THREAD

**Issue by leodarkseid** [InternetHealthReport/ihr-django#33]
The view of the UMS is getting the input data directly from the request object and then, the model is directly bypassed to create a new user thus none of the data is validated, email can contain any field e.g "email" and user will still be created same applies to the password

**Comment by romain-fontugne** [comment]
Thanks, that's not good! are you planning to fix this, I can assign you this issue?

**Comment by leodarkseid** [comment]
Yes, I will

**Comment by leodarkseid** [comment]
@romain-fontugne
