### ISSUE TITLE
IP Endpoint Name is always empty for Network Delay Alarms Endpoint

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-django#45]
## Problem
IP Endpoint Type is always empty for Network Delay Alarms Endpoint e.g:
```json
{
"timebin": "2023-09-15T01:45:00Z",
"startpoint_type": "AS",
"startpoint_name": "206924",
"startpoint_af": 4,
"endpoint_type": "IP",
"endpoint_name": "",
"endpoint_af": 4,
"deviation": 22.5072843440702
}
```

## To Reproduce
1. Query Network Delay Alarms Endpoint e.g using this URL:
https://ihr.iijlab.net/ihr/api/network_delay/alarms/?format=json&deviation__gte=20&startpoint_type=AS&timebin__gte=2023-09-15T00:00:00.000Z&timebin__lte=2023-09-15T23:59:59.000Z
2. Search for the alarm where `endpoint_type` is Equal to `IP`
3. You will find the `endpoint_name` is always an empty string

## Expected Behavior
Endpoint name for IP type shouldn't be always empty

**Comment by romain-fontugne** [comment]
This is actually normal. We don't have yet IP addresses in the database. The empty IP endpoint represents all IP addresses. That means the startpoint has anomalous delays for the majority of IPs seen in the delay measurements

**Comment by mohamedawnallah** [comment]
Aha Got it that makes sense now!
