### ISSUE TITLE
Reverse for 'discoData' not found. 'discoData' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by Forchapeatl** [InternetHealthReport/ihr-django#62]
After including `discoGeoData` and `discoDetail` on [ihr/urls.py](https://github.com/InternetHealthReport/ihr-django/blob/master/urls.py) 
```py
app_name = 'ihr'
urlpatterns = [
    url(r'^discoDetail/<int:pk>/$', views.DiscoDetail.as_view(), name='discoDetail'),
    url(r'^discoGeoData/$', discoGeoData, name='discoGeoData'),
```
 I get this new error when running `./manage.py runserver` , I get error Reverse for 'discoData' not found. 'discoData' is not a valid view function or pattern name.  on http://127.0.0.1:8000/
![image](https://github.com/InternetHealthReport/ihr-django/assets/24577149/91a1f6d9-1222-4af9-81be-9a87aa2dea57)

**Comment by romain-fontugne** [comment]
Thanks for the issue but you should be more explicit. Is this creating any problem? What do you want to do about that? I believe this api endpoint is actually not needed anymore so it could be just removed from the code

**Comment by Forchapeatl** [comment]
I am Sorry about that. My initial solution was to include  this view to the ihr/urls.py

```py
   url(r'^discoData/$', discoData, name='discoData'),

```
 
Thank you for the insight on your approach . This means we have to remove the discoData function from views.py.

https://github.com/InternetHealthReport/ihr-django/blob/da08bf704631a697547dd9dc868edc63eed4b0d1/views.py#L1837-L1896
 
and the commented instance of it at 
https://github.com/InternetHealthReport/ihr-django/blob/da08bf704631a697547dd9dc868edc63eed4b0d1/views.py#L1980

we also have to remove it from all the template files  listed below:

https://github.com/InternetHealthReport/ihr-django/blob/da08bf704631a697547dd9dc868edc63eed4b0d1/templates/ihr/asn_detail.html#L229

https://github.com/InternetHealthReport/ihr-django/blob/da08bf704631a697547dd9dc868edc63eed4b0d1/templates/ihr/index.html#L230

https://github.com/InternetHealthReport/ihr-django/blob/da08bf704631a697547dd9dc868edc63eed4b0d1/templates/ihr/country_detail.html#L103

@romain-fontugne please are there any other depreciated functions which you would like to remove ?

**Comment by romain-fontugne** [comment]
thanks!
Yes, I think all the *Data are not used (delayData, forwardingData, discoGeoData, discoData, hegemonyData, coneData)  and also eventToStepGraph.

Feel free to clean this if you have time to work on this :)

**Comment by Forchapeatl** [comment]
starting with `discoDetail`

**Comment by Forchapeatl** [comment]
Hello @romain-fontugne , please which do you prefer, should I handle each function removal as individual Pull Requests, or should I bundle it up in a singe Pull request?
